### ISSUE TITLE
Need a way to turn off zypper repo priority elevation

### ISSUE THREAD

**Issue by smithfarm** [rjfd/sesdev#18]
Repos listed in `VERSION_OS_REPO_MAPPING` get an elevated priority, but this is not desired. (These repos are maintained and are not expected to have problems with version numbers.)

It's possible to specify custom zypper repos on the command line, but they automatically get an elevated priority setting which may not be desired.

When the repos are sane, elevated repo priority should not be needed. For custom repos specified on the command line, we can keep the default to support users who might be surprised to see their custom repo not being used. But there needs to be a way to turn off the priority elevation.

Conclusion:

* implement a `--no-repo-priority` option providing the user a way to completely disable priority elevation
* drop priority elevation for repos hard-coded in  `VERSION_OS_REPO_MAPPING`

**Comment by rjfd** [comment]
@smithfarm Should we add the SES6 devel repo by default to sesdev?

**Comment by smithfarm** [comment]
@rjfd You removed the priority setting in `v1.1.0` ?

**Comment by smithfarm** [comment]
Yes, I think the devel repo should be added by default to all `SES*`

**Comment by smithfarm** [comment]
@rjfd I brought up a ses6 cluster and the Devel:Storage:6.0 repo is there. It has a higher priority, but that's not a fatal flaw.

**Comment by smithfarm** [comment]
I see now how the priority elevation is done in `1.1.0` - this feature is still needed.
